DROP TABLE "BOARD_IMAGE";
DROP TABLE "BOARD";
DROP TABLE "WELFARE_FACILITY_JOB";
DROP TABLE "AUTH_KEY";
DROP TABLE "WELFARE";
DROP TABLE "COMMENTS";
DROP TABLE "BOARD_TYPE";
DROP TABLE "REGION";
DROP TABLE "COMMENT_LIKE";
DROP TABLE "LOCAL_SUBCATEGORY";
DROP TABLE "MEMBER_CHAT_MESSAGE";
DROP TABLE "BOARD_LIKE";
DROP TABLE "MEMBER";
DROP TABLE "WELFARE_FACILITY";
DROP TABLE "BOARD_HASHTAG";
DROP TABLE "MEMBER_CHAT_ROOM";

CREATE TABLE "BOARD_IMAGE" (
	"IMAGE_NO"	NUMBER		NOT NULL,
	"IMAGE_PATH"	NVARCHAR2(200)		NOT NULL,
	"IMAGE_ORDER"	NUMBER		NOT NULL,
	"IMAGE_NAME"	NVARCHAR2(50)		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

SELECT * FROM "MEMBER" m ;

COMMENT ON COLUMN "BOARD_IMAGE"."IMAGE_NO" IS '게시글 이미지 고유번호(PK)';

COMMENT ON COLUMN "BOARD_IMAGE"."IMAGE_PATH" IS '게시글 이미지 경로';

COMMENT ON COLUMN "BOARD_IMAGE"."IMAGE_ORDER" IS '게시글 이미지 순서';

COMMENT ON COLUMN "BOARD_IMAGE"."IMAGE_NAME" IS '게시글 이미지 명';

COMMENT ON COLUMN "BOARD_IMAGE"."BOARD_NO" IS '게시글 고유번호(PK)';

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TITLE"	NVARCHAR2(1000)		NOT NULL,
	"BOARD_CONTENT"	NVARCHAR2(2000)		NOT NULL,
	"BOARD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_UPDATE"	DATE		NULL,
	"BOARD_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"BOARD_ANSWER"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"BOARD_TYPE"	NUMBER		NOT NULL,
	"STAR_COUNT"	NUMBER		NULL,
	"POST_TYPE"	VARCHAR2(50)		NULL,
	"BOARD_REPORT_COUNT"	NUMBER	DEFAULT 0	NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"API_SERVICE_ID"	VARCHAR2(100)	NOT NULL,
	"FACILITY_API_SERVICE_ID"	VARCHAR2(100)	NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 고유번호(PK)';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시판 제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD"."BOARD_DATE" IS '게시글 작성일';

COMMENT ON COLUMN "BOARD"."BOARD_DEL_FL" IS '게시글 삭제여부(Y/N)';

COMMENT ON COLUMN "BOARD"."BOARD_ANSWER" IS '관리자 답변여부(Y/N)';

COMMENT ON COLUMN "BOARD"."BOARD_TYPE" IS '게시글 코드번호(1: 공지, 2:문의, 3:우리동네)';

COMMENT ON COLUMN "BOARD"."STAR_COUNT" IS '별점수(max5)';

COMMENT ON COLUMN "BOARD"."POST_TYPE" IS '후기/자유: 우리동네 게시판만 사용';

COMMENT ON COLUMN "BOARD"."BOARD_REPORT_COUNT" IS '게시글 신고 횟수';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '작성자회원번호';

COMMENT ON COLUMN "BOARD"."API_SERVICE_ID" IS '유니크 조건 필수';

COMMENT ON COLUMN "BOARD"."FACILITY_API_SERVICE_ID" IS '유니크 조건 필수(FACILITY)';

CREATE TABLE "WELFARE_FACILITY_JOB" (
	"JOB_NO"	NUMBER		NOT NULL,
	"JOB_API_SERVICE_ID"	VARCHAR2(100)	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"JOB_TITLE"	VARCHAR2(200)		NULL,
	"JOB_SALARY"	VARCHAR2(200)		NULL,
	"JOB_POSITION"	VARCHAR2(100)		NULL,
	"JOB_CONTACT"	VARCHAR2(100)		NULL,
	"JOB_CONTACT_TEL"	VARCHAR2(20)		NULL,
	"JOB_REQUIREMENT"	VARCHAR2(1000)		NULL,
	"JOB_ADDRESS"	VARCHAR2(100)		NOT NULL,
	"LAT"	NUMBER		NULL,
	"LNG"	NUMBER		NULL,
	"RCPTBGNDT"	NVARCHAR2(20)		NULL,
	"RCPTENDDT"	NVARCHAR2(20)		NULL,
	"JJ_TIME"	DATE	DEFAULT SYSDATE	NOT NULL,
	"UPDATED_AT"	DATE		NULL,
	"JJ_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"ALARM_SENT_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"REGION_DISTRICT"	VARCHAR2(100)		NOT NULL,
	"REGION_CITY"	VARCHAR2(100)		NOT NULL,
	"JOB_FACILITY_NAME" VARCHAR2(100) NULL,
	"JOB_CONTENT" VARCHAR2(1000) NULL	
);

COMMENT ON COLUMN "WELFARE_FACILITY_JOB"."JOB_FACILITY_NAME" IS '채용번호기관';

COMMENT ON COLUMN "WELFARE_FACILITY_JOB"."JOB_CONTENT" IS '채용 정보';

COMMENT ON COLUMN "WELFARE_FACILITY_JOB"."JOB_NO" IS '채용번호(PK)';

COMMENT ON COLUMN "WELFARE_FACILITY_JOB"."JOB_API_SERVICE_ID" IS '유니크 조건 필수';

COMMENT ON COLUMN "WELFARE_FACILITY_JOB"."MEMBER_NO" IS '회원 고유번호(PK)';

COMMENT ON COLUMN "WELFARE_FACILITY_JOB"."JOB_TITLE" IS '채용 제목';

COMMENT ON COLUMN "WELFARE_FACILITY_JOB"."JOB_SALARY" IS '임금조건';

COMMENT ON COLUMN "WELFARE_FACILITY_JOB"."JOB_POSITION" IS '채용분야';

COMMENT ON COLUMN "WELFARE_FACILITY_JOB"."JOB_CONTACT" IS '담당자명';

COMMENT ON COLUMN "WELFARE_FACILITY_JOB"."JOB_CONTACT_TEL" IS '담당자 전화';

COMMENT ON COLUMN "WELFARE_FACILITY_JOB"."JOB_REQUIREMENT" IS '자격조건 요약';

COMMENT ON COLUMN "WELFARE_FACILITY_JOB"."JOB_ADDRESS" IS '채용기관 주소';

COMMENT ON COLUMN "WELFARE_FACILITY_JOB"."LAT" IS '위도';

COMMENT ON COLUMN "WELFARE_FACILITY_JOB"."LNG" IS '경도';

COMMENT ON COLUMN "WELFARE_FACILITY_JOB"."RCPTBGNDT" IS '접수일시';

COMMENT ON COLUMN "WELFARE_FACILITY_JOB"."RCPTENDDT" IS '접수종료일시';

COMMENT ON COLUMN "WELFARE_FACILITY_JOB"."JJ_TIME" IS '찜시간';

COMMENT ON COLUMN "WELFARE_FACILITY_JOB"."UPDATED_AT" IS '알림 발송 시간';

COMMENT ON COLUMN "WELFARE_FACILITY_JOB"."JJ_DEL_FL" IS '찜 취소 여부';

COMMENT ON COLUMN "WELFARE_FACILITY_JOB"."REGION_DISTRICT" IS '시군구명';

COMMENT ON COLUMN "WELFARE_FACILITY_JOB"."REGION_CITY" IS '시도';

CREATE TABLE "AUTH_KEY" (
	"AUTH_KEY_NO"	NUMBER		NOT NULL,
	"EMAIL"	NVARCHAR2(50)		NOT NULL,
	"AUTH_KEY"	CHAR(6)		NOT NULL,
	"CREATE_TIME"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY_NO" IS '인증키 구분번호(PK)';

COMMENT ON COLUMN "AUTH_KEY"."EMAIL" IS '인증 이메일';

COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY" IS '인증번호';

COMMENT ON COLUMN "AUTH_KEY"."CREATE_TIME" IS '인증번호 생성';

CREATE TABLE "WELFARE" (
	"SERVICE_NO"	NUMBER		NOT NULL,
	"API_SERVICE_ID"	VARCHAR2(100)	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"AGENCY"	VARCHAR2(200)		NOT NULL,
	"SERVICE_NAME"	VARCHAR2(400)		NOT NULL,
	"DESCRIPTION"	CLOB		NULL,
	"CATEGORY"	VARCHAR2(100)		NOT NULL,
	"RECEPTION_METHOD"	VARCHAR2(200)		NULL,
	"RECEPTION_START"	NVARCHAR2(20)		NULL,
	"RECEPTION_END"	NVARCHAR2(20)		NULL,
	"URL"	VARCHAR2(500)		NULL,
	"SERVICE_PAY"	NUMBER		NULL,
	"LAT"	NUMBER		NULL,
	"LNG"	NUMBER		NULL,
	"REGION_DISTRICT"	VARCHAR2(100)		NOT NULL,
	"REGION_CITY"	VARCHAR2(100)		NOT NULL,
	"JJ_TIME"	DATE		NOT NULL,
	"UPDATED_AT"	DATE		NULL,
	"JJ_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"ALARM_SENT_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

CREATE SEQUENCE welfare_seq START WITH 1 INCREMENT BY 1 NOCACHE;


COMMENT ON COLUMN "WELFARE"."SERVICE_NO" IS '서비스 번호(PK)';

COMMENT ON COLUMN "WELFARE"."API_SERVICE_ID" IS '유니크 조건 필수';

COMMENT ON COLUMN "WELFARE"."MEMBER_NO" IS '회원 고유번호(PK)';

COMMENT ON COLUMN "WELFARE"."AGENCY" IS '제공기관명';

COMMENT ON COLUMN "WELFARE"."SERVICE_NAME" IS '복지 서비스명';

COMMENT ON COLUMN "WELFARE"."DESCRIPTION" IS '복지 상세 설명';

COMMENT ON COLUMN "WELFARE"."CATEGORY" IS '복지 분류 (노인/아동/장애 등)';

COMMENT ON COLUMN "WELFARE"."RECEPTION_METHOD" IS '신청 방법';

COMMENT ON COLUMN "WELFARE"."RECEPTION_START" IS '신청 시작일';

COMMENT ON COLUMN "WELFARE"."RECEPTION_END" IS '신청 마감일';

COMMENT ON COLUMN "WELFARE"."URL" IS '상세 안내 URL';

COMMENT ON COLUMN "WELFARE"."SERVICE_PAY" IS '유료 여뷰';

COMMENT ON COLUMN "WELFARE"."LAT" IS '위도';

COMMENT ON COLUMN "WELFARE"."LNG" IS '경도';

COMMENT ON COLUMN "WELFARE"."REGION_DISTRICT" IS '시군구명';

COMMENT ON COLUMN "WELFARE"."REGION_CITY" IS '시도';

COMMENT ON COLUMN "WELFARE"."JJ_TIME" IS '찜시간';

COMMENT ON COLUMN "WELFARE"."UPDATED_AT" IS '알림 발송 시간';

COMMENT ON COLUMN "WELFARE"."JJ_DEL_FL" IS '찜 취소 여부';

CREATE TABLE "COMMENTS" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"COMMENT_CONTENT"	NVARCHAR2(1500)		NOT NULL,
	"COMMENT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"COMMENT_UPDATE_DATE"	DATE		NULL,
	"COMMENT_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"COMMENT_PARENT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "COMMENTS"."COMMENT_NO" IS '댓글 고유번호(PK)';

COMMENT ON COLUMN "COMMENTS"."COMMENT_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "COMMENTS"."COMMENT_DATE" IS '댓글 작성일';

COMMENT ON COLUMN "COMMENTS"."COMMENT_UPDATE_DATE" IS '댓글 수정일';

COMMENT ON COLUMN "COMMENTS"."COMMENT_DEL_FL" IS '댓글 삭제 여부';

COMMENT ON COLUMN "COMMENTS"."BOARD_NO" IS '게시글 고유번호(PK)';

COMMENT ON COLUMN "COMMENTS"."MEMBER_NO" IS '회원 고유번호(PK)';

COMMENT ON COLUMN "COMMENTS"."COMMENT_PARENT_NO" IS '부모 댓글 고유번호(FK)';

CREATE TABLE "BOARD_TYPE" (
	"BOARD_CODE"	NUMBER		NOT NULL,
	"BOARD_NAME"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_CODE" IS '게시글 코드번호(1: 공지, 2:문의, 3:우리동네)';

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_NAME" IS '게시판명';

CREATE TABLE "REGION" (
	"REGION_DISTRICT"	VARCHAR2(100)		NOT NULL,
	"REGION_CITY"	VARCHAR2(100)		NOT NULL,
	"DATASET_ID"	VARCHAR2(50)		NULL,
	"UDDI_ID"	VARCHAR2(100)		NULL
);

COMMENT ON COLUMN "REGION"."REGION_DISTRICT" IS '시군구명';

COMMENT ON COLUMN "REGION"."REGION_CITY" IS '시도';

CREATE TABLE "COMMENT_LIKE" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"COMMENT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "COMMENT_LIKE"."MEMBER_NO" IS '회원 고유번호(PK)';

COMMENT ON COLUMN "COMMENT_LIKE"."COMMENT_NO" IS '댓글 고유번호(PK)';

CREATE TABLE "LOCAL_SUBCATEGORY" (
	"POST_TYPE"	VARCHAR2(50)		NOT NULL,
	"BOARD_TYPE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "LOCAL_SUBCATEGORY"."POST_TYPE" IS '후기/자유: 우리동네 게시판만 사용';

COMMENT ON COLUMN "LOCAL_SUBCATEGORY"."BOARD_TYPE" IS '게시글 코드번호(1: 공지, 2:문의, 3:우리동네)';

CREATE TABLE "MEMBER_CHAT_MESSAGE" (
	"CHAT_NO"	NUMBER		NOT NULL,
	"SENDER_NO"	NUMBER		NOT NULL,
	"CHAT_CONTENT"	NVARCHAR2(2000)		NULL,
	"CHAT_READ_FL"	CHAR(1)		NOT NULL,
	"CHAT_SEND_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"CHAT_CONTENT_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"CHAT_ROOM_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MEMBER_CHAT_MESSAGE"."CHAT_NO" IS '메세지번호(PK)';

COMMENT ON COLUMN "MEMBER_CHAT_MESSAGE"."SENDER_NO" IS '회원 고유번호(PK)';

COMMENT ON COLUMN "MEMBER_CHAT_MESSAGE"."CHAT_CONTENT" IS '메세지 내용';

COMMENT ON COLUMN "MEMBER_CHAT_MESSAGE"."CHAT_READ_FL" IS '메세지 읽음 유무';

COMMENT ON COLUMN "MEMBER_CHAT_MESSAGE"."CHAT_SEND_DATE" IS '메세지 보낸 시간';

COMMENT ON COLUMN "MEMBER_CHAT_MESSAGE"."CHAT_CONTENT_DEL_FL" IS '메세지 삭제 여부';

COMMENT ON COLUMN "MEMBER_CHAT_MESSAGE"."CHAT_ROOM_NO" IS '채팅방 번호(PK)';

CREATE TABLE "BOARD_LIKE" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_LIKE"."MEMBER_NO" IS '회원 고유번호(PK)';

COMMENT ON COLUMN "BOARD_LIKE"."BOARD_NO" IS '게시글 고유번호(PK)';

CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	NVARCHAR2(15)		NOT NULL,
	"MEMBER_PW"	NVARCHAR2(20)		NOT NULL,
	"MEMBER_NICKNAME"	NVARCHAR2(10)		NOT NULL,
	"MEMBER_EMAIL"	NVARCHAR2(50)		NOT NULL,
	"MEMBER_TEL"	CHAR(11)		NOT NULL,
	"MEMBER_ADDRESS"	NVARCHAR2(300)		NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_IMG"	NVARCHAR2(300)		NULL,
	"AUTHORITY"	NUMBER	DEFAULT 1	NOT NULL,
	"MEMBER_TADDRESS"	NVARCHAR2(300)		NULL,
	"MEMBER_STANDARD"	CHAR(1)		NOT NULL,
	"MEMBER_PW_CH"	NVARCHAR2(20)		NULL,
	"REGION_DISTRICT"	VARCHAR2(100)		NOT NULL,
	"REGION_CITY"	VARCHAR2(100)		NOT NULL,
	"REPORT_COUNT"	NUMBER	DEFAULT 0	NULL,
	"SUSPENDED_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"KAKAO_ID"	NVARCHAR2(15)		NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 고유번호(PK)';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원 닉네임';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일';

COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '회원 전화번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_ADDRESS" IS '회원 주소';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '회원 가입 날짜';

COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '회원 삭제 여부';

COMMENT ON COLUMN "MEMBER"."MEMBER_IMG" IS '회원 이미지';

COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '회원 권한';

COMMENT ON COLUMN "MEMBER"."MEMBER_TADDRESS" IS '회원 임시주소';

COMMENT ON COLUMN "MEMBER"."MEMBER_STANDARD" IS '계층 대상자';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW_CH" IS '회원 비밀번호 확인';

COMMENT ON COLUMN "MEMBER"."REGION_DISTRICT" IS '시군구명';

COMMENT ON COLUMN "MEMBER"."REGION_CITY" IS '시도';

COMMENT ON COLUMN "MEMBER"."REPORT_COUNT" IS '신고 누적 횟수';

COMMENT ON COLUMN "MEMBER"."SUSPENDED_FL" IS '사용 정지 여부';

COMMENT ON COLUMN "MEMBER"."KAKAO_ID" IS '카카오 회원 아이디';

CREATE TABLE "WELFARE_FACILITY" (
	"FACILITY_NO"	VARCHAR2(100)		NOT NULL,
	"FACILITY_API_SERVICE_ID"	VARCHAR2(100)	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"FACILITY_NAME"	VARCHAR2(200)		NOT NULL,
	"FACILITY_KIND_CD"	VARCHAR2(10)		NOT NULL,
	"FACILITY_KIND_NM"	VARCHAR2(100)		NULL,
	"FACILITY_BIZNO"	VARCHAR2(20)		NULL,
	"OWNER"	VARCHAR2(100)		NULL,
	"FACILITY_TEL"	VARCHAR2(20)		NULL,
	"FACILITY_EMAIL"	VARCHAR2(300)	DEFAULT '정보없음'	NULL,
	"FACILITY_ADDR"	VARCHAR2(300)		NOT NULL,
	"FACILITY_HOMEPAGE"	VARCHAR2(200)		NULL,
	"BUILDING_NO"	VARCHAR2(30)		NULL,
	"EVENT_TITLE"	VARCHAR2(200)		NULL,
	"EVENT_DATE_START"	NVARCHAR2(20)		NULL,
	"EVENT_DATE_END"	NVARCHAR2(20)		NULL,
	"EVENT_CONTENT"	VARCHAR2(1000)		NULL,
	"CONTACT_TEL"	VARCHAR2(20)		NULL,
	"REQUIREMENT"	VARCHAR2(1000)		NULL,
	"LAT"	NUMBER		NULL,
	"LNG"	NUMBER		NULL,
	"REGION_DISTRICT"	VARCHAR2(100)		NOT NULL,
	"REGION_CITY"	VARCHAR2(100)		NOT NULL,
	"RCPTBGNDT"	NVARCHAR2(20)		NULL,
	"RCPTENDDT"	NVARCHAR2(20)		NULL,
	"JJ_TIME"	DATE		NOT NULL,
	"UPDATED_AT"	DATE		NULL,
	"JJ_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"ALARM_SENT_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "WELFARE_FACILITY"."FACILITY_NO" IS '시설 서비스 번호(PK)';

COMMENT ON COLUMN "WELFARE_FACILITY"."FACILITY_API_SERVICE_ID" IS '유니크 조건 필수';

COMMENT ON COLUMN "WELFARE_FACILITY"."MEMBER_NO" IS '회원 고유번호(PK)';

COMMENT ON COLUMN "WELFARE_FACILITY"."FACILITY_NAME" IS '시설명';

COMMENT ON COLUMN "WELFARE_FACILITY"."FACILITY_KIND_CD" IS '시설종류 코드';

COMMENT ON COLUMN "WELFARE_FACILITY"."FACILITY_KIND_NM" IS '시설종류명';

COMMENT ON COLUMN "WELFARE_FACILITY"."FACILITY_BIZNO" IS '사업자등록번호';

COMMENT ON COLUMN "WELFARE_FACILITY"."OWNER" IS '대표자명';

COMMENT ON COLUMN "WELFARE_FACILITY"."FACILITY_TEL" IS '전화번호';

COMMENT ON COLUMN "WELFARE_FACILITY"."FACILITY_EMAIL" IS '이메일주소';

COMMENT ON COLUMN "WELFARE_FACILITY"."FACILITY_ADDR" IS '주소';

COMMENT ON COLUMN "WELFARE_FACILITY"."FACILITY_HOMEPAGE" IS '홈페이지주소';

COMMENT ON COLUMN "WELFARE_FACILITY"."BUILDING_NO" IS '건물관리번호';

COMMENT ON COLUMN "WELFARE_FACILITY"."EVENT_TITLE" IS '행사 제목';

COMMENT ON COLUMN "WELFARE_FACILITY"."EVENT_DATE_START" IS '행사 시작일';

COMMENT ON COLUMN "WELFARE_FACILITY"."EVENT_DATE_END" IS '행사 종료일';

COMMENT ON COLUMN "WELFARE_FACILITY"."EVENT_CONTENT" IS '행사 내용 요약';

COMMENT ON COLUMN "WELFARE_FACILITY"."CONTACT_TEL" IS '담당자 전화';

COMMENT ON COLUMN "WELFARE_FACILITY"."REQUIREMENT" IS '입장 가능 기준 조건';

COMMENT ON COLUMN "WELFARE_FACILITY"."LAT" IS '위도';

COMMENT ON COLUMN "WELFARE_FACILITY"."LNG" IS '경도';

COMMENT ON COLUMN "WELFARE_FACILITY"."REGION_DISTRICT" IS '시군구명';

COMMENT ON COLUMN "WELFARE_FACILITY"."REGION_CITY" IS '시도';

COMMENT ON COLUMN "WELFARE_FACILITY"."RCPTBGNDT" IS '접수일시';

COMMENT ON COLUMN "WELFARE_FACILITY"."RCPTENDDT" IS '접수종료일시';

COMMENT ON COLUMN "WELFARE_FACILITY"."JJ_TIME" IS '찜시간';

COMMENT ON COLUMN "WELFARE_FACILITY"."UPDATED_AT" IS '알림 발송 시간';

COMMENT ON COLUMN "WELFARE_FACILITY"."JJ_DEL_FL" IS '찜 취소 여부';

CREATE TABLE "BOARD_HASHTAG" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"HASHTAG_NAME"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "BOARD_HASHTAG"."BOARD_NO" IS '게시글 고유번호(PK)';

COMMENT ON COLUMN "BOARD_HASHTAG"."HASHTAG_NAME" IS '해시태그명';

CREATE TABLE "MEMBER_CHAT_ROOM" (
	"CHAT_ROOM_NO"	NUMBER		NOT NULL,
	"OPEN_MEMBER"	NUMBER		NOT NULL,
	"PARTICIPANT"	NUMBER		NOT NULL,
	"CHAT_CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"CHAT_ROOM_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "MEMBER_CHAT_ROOM"."CHAT_ROOM_NO" IS '채팅방 번호(PK)';

COMMENT ON COLUMN "MEMBER_CHAT_ROOM"."OPEN_MEMBER" IS '채팅 오픈 회원(MEMBER_PK)';

COMMENT ON COLUMN "MEMBER_CHAT_ROOM"."PARTICIPANT" IS '참여 회원(MEMBER_PK)';

COMMENT ON COLUMN "MEMBER_CHAT_ROOM"."CHAT_CREATE_DATE" IS '채팅방 생성 시간';

COMMENT ON COLUMN "MEMBER_CHAT_ROOM"."CHAT_ROOM_DEL_FL" IS '채팅방 삭제 여부';



-- BOARD 테이블
ALTER TABLE "BOARD"
ADD CONSTRAINT "UQ_BOARD_API_SERVICE_ID" UNIQUE ("API_SERVICE_ID");

ALTER TABLE "BOARD"
ADD CONSTRAINT "UQ_BOARD_FACILITY_API_SERVICE_ID" UNIQUE ("FACILITY_API_SERVICE_ID");

-- WELFARE 테이블
ALTER TABLE "WELFARE"
ADD CONSTRAINT "UQ_WELFARE_API_SERVICE_ID" UNIQUE ("API_SERVICE_ID");

-- WELFARE_FACILITY 테이블
ALTER TABLE "WELFARE_FACILITY"
ADD CONSTRAINT "UQ_WELFARE_FACILITY_API_SERVICE_ID" UNIQUE ("FACILITY_API_SERVICE_ID");

-- WELFARE_FACILITY_JOB 테이블
ALTER TABLE "WELFARE_FACILITY_JOB"
ADD CONSTRAINT "UQ_WELFARE_FACILITY_JOB_API_SERVICE_ID" UNIQUE ("JOB_API_SERVICE_ID");


ALTER TABLE "BOARD_IMAGE" ADD CONSTRAINT "PK_BOARD_IMAGE" PRIMARY KEY (
	"IMAGE_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "WELFARE_FACILITY_JOB" ADD CONSTRAINT "PK_WELFARE_FACILITY_JOB" PRIMARY KEY (
	"JOB_NO",
	"JOB_API_SERVICE_ID",
	"MEMBER_NO"
);

ALTER TABLE "AUTH_KEY" ADD CONSTRAINT "PK_AUTH_KEY" PRIMARY KEY (
	"AUTH_KEY_NO"
);

ALTER TABLE "WELFARE" ADD CONSTRAINT "PK_WELFARE" PRIMARY KEY (
	"SERVICE_NO",
	"API_SERVICE_ID",
	"MEMBER_NO"
);

ALTER TABLE "COMMENTS" ADD CONSTRAINT "PK_COMMENTS" PRIMARY KEY (
	"COMMENT_NO"
);

ALTER TABLE "BOARD_TYPE" ADD CONSTRAINT "PK_BOARD_TYPE" PRIMARY KEY (
	"BOARD_CODE"
);

ALTER TABLE "REGION" ADD CONSTRAINT "PK_REGION" PRIMARY KEY (
	"REGION_DISTRICT",
	"REGION_CITY"
);

ALTER TABLE "COMMENT_LIKE" ADD CONSTRAINT "PK_COMMENT_LIKE" PRIMARY KEY (
	"MEMBER_NO",
	"COMMENT_NO"
);

ALTER TABLE "LOCAL_SUBCATEGORY" ADD CONSTRAINT "PK_LOCAL_SUBCATEGORY" PRIMARY KEY (
	"POST_TYPE",
	"BOARD_TYPE"
);

ALTER TABLE "MEMBER_CHAT_MESSAGE" ADD CONSTRAINT "PK_MEMBER_CHAT_MESSAGE" PRIMARY KEY (
	"CHAT_NO"
);

ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "PK_BOARD_LIKE" PRIMARY KEY (
	"MEMBER_NO",
	"BOARD_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "WELFARE_FACILITY" ADD CONSTRAINT "PK_WELFARE_FACILITY" PRIMARY KEY (
	"FACILITY_NO",
	"FACILITY_API_SERVICE_ID",
	"MEMBER_NO"
);

ALTER TABLE "MEMBER_CHAT_ROOM" ADD CONSTRAINT "PK_MEMBER_CHAT_ROOM" PRIMARY KEY (
	"CHAT_ROOM_NO"
);

ALTER TABLE "BOARD_IMAGE" ADD CONSTRAINT "FK_BOARD_TO_BOARD_IMAGE_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_BOARD_TYPE_TO_BOARD_1" FOREIGN KEY (
	"BOARD_TYPE"
)
REFERENCES "BOARD_TYPE" (
	"BOARD_CODE"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_WELFARE_TO_BOARD_1" FOREIGN KEY (
	"API_SERVICE_ID"
)
REFERENCES "WELFARE" (
	"API_SERVICE_ID"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_WELFARE_FACILITY_TO_BOARD_1" FOREIGN KEY (
	"FACILITY_API_SERVICE_ID"
)
REFERENCES "WELFARE_FACILITY" (
	"FACILITY_API_SERVICE_ID"
);

ALTER TABLE "WELFARE_FACILITY_JOB" ADD CONSTRAINT "FK_MEMBER_TO_WELFARE_FACILITY_JOB_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

-- 복합외래키 설정
ALTER TABLE "REGION"
ADD CONSTRAINT "UQ_REGION_COMPOSITE"
UNIQUE ("REGION_CITY", "REGION_DISTRICT");

-- 복합 외래키
ALTER TABLE "WELFARE_FACILITY_JOB"
ADD CONSTRAINT "FK_REGION_TO_WELFARE_FACILITY_JOB"
FOREIGN KEY ("REGION_CITY", "REGION_DISTRICT")
REFERENCES "REGION" ("REGION_CITY", "REGION_DISTRICT");

-- 복합외래키 설정
ALTER TABLE "WELFARE"
ADD CONSTRAINT "FK_REGION_TO_WELFARE"
FOREIGN KEY ("REGION_CITY", "REGION_DISTRICT")
REFERENCES "REGION" ("REGION_CITY", "REGION_DISTRICT");


-- 복합외래키 설정
ALTER TABLE "WELFARE_FACILITY"
ADD CONSTRAINT "FK_REGION_TO_WELFARE_FACILITY"
FOREIGN KEY ("REGION_CITY", "REGION_DISTRICT")
REFERENCES "REGION" ("REGION_CITY", "REGION_DISTRICT");


ALTER TABLE "WELFARE" ADD CONSTRAINT "FK_MEMBER_TO_WELFARE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);


ALTER TABLE "COMMENTS" ADD CONSTRAINT "FK_BOARD_TO_COMMENTS_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "COMMENTS" ADD CONSTRAINT "FK_MEMBER_TO_COMMENTS_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "COMMENTS" ADD CONSTRAINT "FK_COMMENTS_TO_COMMENTS_1" FOREIGN KEY (
	"COMMENT_PARENT_NO"
)
REFERENCES "COMMENTS" (
	"COMMENT_NO"
);

ALTER TABLE "COMMENT_LIKE" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_LIKE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "COMMENT_LIKE" ADD CONSTRAINT "FK_COMMENTS_TO_COMMENT_LIKE_1" FOREIGN KEY (
	"COMMENT_NO"
)
REFERENCES "COMMENTS" (
	"COMMENT_NO"
);

ALTER TABLE "LOCAL_SUBCATEGORY" ADD CONSTRAINT "FK_BOARD_TYPE_TO_LOCAL_SUBCATEGORY_1" FOREIGN KEY (
	"BOARD_TYPE"
)
REFERENCES "BOARD_TYPE" (
	"BOARD_CODE"
);

ALTER TABLE "MEMBER_CHAT_MESSAGE" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_CHAT_MESSAGE_1" FOREIGN KEY (
	"SENDER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "MEMBER_CHAT_MESSAGE" ADD CONSTRAINT "FK_MEMBER_CHAT_ROOM_TO_MEMBER_CHAT_MESSAGE_1" FOREIGN KEY (
	"CHAT_ROOM_NO"
)
REFERENCES "MEMBER_CHAT_ROOM" (
	"CHAT_ROOM_NO"
);

ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_LIKE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "FK_BOARD_TO_BOARD_LIKE_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

-- 복합외래키 설정
ALTER TABLE "MEMBER"
ADD CONSTRAINT "FK_REGION_TO_MEMBER"
FOREIGN KEY ("REGION_CITY", "REGION_DISTRICT")
REFERENCES "REGION" ("REGION_CITY", "REGION_DISTRICT");

ALTER TABLE "WELFARE_FACILITY" ADD CONSTRAINT "FK_MEMBER_TO_WELFARE_FACILITY_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);


ALTER TABLE "BOARD_HASHTAG" ADD CONSTRAINT "FK_BOARD_TO_BOARD_HASHTAG_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "MEMBER_CHAT_ROOM" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_CHAT_ROOM_1" FOREIGN KEY (
	"OPEN_MEMBER"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "MEMBER_CHAT_ROOM" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_CHAT_ROOM_2" FOREIGN KEY (
	"PARTICIPANT"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE BOARD MODIFY API_SERVICE_ID VARCHAR2(100) NULL;
ALTER TABLE BOARD MODIFY FACILITY_API_SERVICE_ID VARCHAR2(100) NULL;


COMMIT;


-- REGION 
INSERT INTO REGION (REGION_CITY, REGION_DISTRICT)
VALUES ('서울시', '강남구');

INSERT INTO REGION (REGION_CITY, REGION_DISTRICT)
VALUES ('부산시', '해운대구');

INSERT INTO REGION (REGION_CITY, REGION_DISTRICT)
VALUES ('대구시', '중구');

INSERT INTO REGION (REGION_CITY, REGION_DISTRICT)
VALUES ('광주시', '동구');

INSERT INTO REGION (REGION_CITY, REGION_DISTRICT)
VALUES ('인천시', '남동구');

COMMIT;

CREATE SEQUENCE SEQ_MEMBER_NO
  START WITH 2
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

SELECT MAX(MEMBER_NO) FROM MEMBER;

INSERT INTO REGION (REGION_CITY, REGION_DISTRICT) VALUES ('경기', '고양시 일산서구');


-- MEMBER
--INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_TEL,
--                    MEMBER_ADDRESS, ENROLL_DATE, MEMBER_DEL_FL, MEMBER_IMG, AUTHORITY,
--                    MEMBER_TADDRESS, MEMBER_STANDARD, MEMBER_PW_CH, REGION_DISTRICT, REGION_CITY,
--                    REPORT_COUNT, SUSPENDED_FL, KAKAO_ID, MEMBER_NAME)
--VALUES (1, 'user01', 'pw1234', '홍길동', 'user01@example.com', '01012345678',
--        '서울 강남구 테헤란로 1', SYSDATE - 10, 'N', NULL, 1,
--        NULL, 'Y', NULL, '강남구', '서울시',
--        0, 'N', NULL, '이순신);

--INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_TEL,
--                    MEMBER_ADDRESS, ENROLL_DATE, MEMBER_DEL_FL, MEMBER_IMG, AUTHORITY,
--                    MEMBER_TADDRESS, MEMBER_STANDARD, MEMBER_PW_CH, REGION_DISTRICT, REGION_CITY,
--                    REPORT_COUNT, SUSPENDED_FL, KAKAO_ID, MEMBER_NAME)
--VALUES (    2, 'user02', 'pw5678', '이순신', 'user02@example.com', '01087654321',
--    '부산 해운대구 센텀중앙로 55', SYSDATE - 8, 'N', NULL, 1,
--    NULL, 'N', 'N', '해운대구', '부산시',
--    0, 'N', NULL);
--
--INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_TEL,
--                    MEMBER_ADDRESS, ENROLL_DATE, MEMBER_DEL_FL, MEMBER_IMG, AUTHORITY,
--                    MEMBER_TADDRESS, MEMBER_STANDARD, MEMBER_PW_CH, REGION_DISTRICT, REGION_CITY,
--                    REPORT_COUNT, SUSPENDED_FL, KAKAO_ID)
--VALUES (3, 'user03', 'pw9012', '장보고', 'user03@example.com', '01099887766',
--        '대구 중구 중앙대로 77', SYSDATE - 6, 'N', NULL, 1,
--        NULL, 'Y', NULL, '중구', '대구시',
--        0, 'N', NULL);
--
--INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_TEL,
--                    MEMBER_ADDRESS, ENROLL_DATE, MEMBER_DEL_FL, MEMBER_IMG, AUTHORITY,
--                    MEMBER_TADDRESS, MEMBER_STANDARD, MEMBER_PW_CH, REGION_DISTRICT, REGION_CITY,
--                    REPORT_COUNT, SUSPENDED_FL, KAKAO_ID)
--VALUES (4, 'user04', 'pw3456', '세종대왕', 'user04@example.com', '01022334455',
--        '광주 동구 금남로 20', SYSDATE - 3, 'N', NULL, 1,
--        NULL, 'N', NULL, '동구', '광주시',
--        0, 'N', NULL);
--
--INSERT INTO MEMBER (MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_NICKNAME, MEMBER_EMAIL, MEMBER_TEL,
--                    MEMBER_ADDRESS, ENROLL_DATE, MEMBER_DEL_FL, MEMBER_IMG, AUTHORITY,
--                    MEMBER_TADDRESS, MEMBER_STANDARD, MEMBER_PW_CH, REGION_DISTRICT, REGION_CITY,
--                    REPORT_COUNT, SUSPENDED_FL, KAKAO_ID)
--VALUES (5, 'user05', 'pw7890', '유관순', 'user05@example.com', '01055667788',
--        '인천 남동구 예술로 100', SYSDATE - 1, 'N', NULL, 1,
--        NULL, 'Y', NULL, '남동구', '인천시',
--        0, 'N', NULL);

COMMIT;


SELECT * FROM WELFARE_FACILITY_JOB;
-- WELFARE_FACILITY_JOB (찜/채용 공고 예시)
INSERT INTO WELFARE_FACILITY_JOB (
  JOB_NO, JOB_API_SERVICE_ID, MEMBER_NO, JOB_TITLE, JOB_SALARY,
  JOB_POSITION, JOB_ADDRESS, REGION_CITY, REGION_DISTRICT
) VALUES (1, 'JOB001', 1, '채용공고 1', '월 210만원', '보조원', '서울 강남구', '서울시', '강남구');

INSERT INTO WELFARE_FACILITY_JOB (
  JOB_NO, JOB_API_SERVICE_ID, MEMBER_NO, JOB_TITLE, JOB_SALARY,
  JOB_POSITION, JOB_ADDRESS, REGION_CITY, REGION_DISTRICT
) VALUES (2, 'JOB002', 2, '채용공고 2', '월 220만원', '사회복지사', '부산 해운대구', '부산시', '해운대구');

INSERT INTO WELFARE_FACILITY_JOB (
  JOB_NO, JOB_API_SERVICE_ID, MEMBER_NO, JOB_TITLE, JOB_SALARY,
  JOB_POSITION, JOB_ADDRESS, REGION_CITY, REGION_DISTRICT
) VALUES (3, 'JOB003', 3, '채용공고 3', '월 230만원', '간병인', '대구 중구', '대구시', '중구');

INSERT INTO WELFARE_FACILITY_JOB (
  JOB_NO, JOB_API_SERVICE_ID, MEMBER_NO, JOB_TITLE, JOB_SALARY,
  JOB_POSITION, JOB_ADDRESS, REGION_CITY, REGION_DISTRICT
) VALUES (4, 'JOB004', 4, '채용공고 4', '월 240만원', '요양보호사', '광주 동구', '광주시', '동구');

INSERT INTO WELFARE_FACILITY_JOB (
  JOB_NO, JOB_API_SERVICE_ID, MEMBER_NO, JOB_TITLE, JOB_SALARY,
  JOB_POSITION, JOB_ADDRESS, REGION_CITY, REGION_DISTRICT
) VALUES (5, 'JOB005', 5, '채용공고 5', '월 250만원', '운전원', '인천 남동구', '인천시', '남동구');


SELECT * FROM WELFARE_FACILITY;
-- WELFARE_FACILITY
INSERT INTO WELFARE_FACILITY (
  FACILITY_NO, FACILITY_API_SERVICE_ID, MEMBER_NO, FACILITY_NAME, FACILITY_KIND_CD, FACILITY_KIND_NM,
  FACILITY_BIZNO, OWNER, FACILITY_TEL, FACILITY_EMAIL, FACILITY_ADDR, FACILITY_HOMEPAGE, BUILDING_NO,
  EVENT_TITLE, EVENT_DATE_START, EVENT_DATE_END, EVENT_CONTENT, CONTACT_TEL, REQUIREMENT,
  LAT, LNG, REGION_DISTRICT, REGION_CITY, RCPTBGNDT, RCPTENDDT, JJ_TIME, UPDATED_AT, JJ_DEL_FL, ALARM_SENT_FL
) VALUES (
  'FAC001', 'FAC001', 1, '서울 복지센터', '01', '노인복지시설', '123-45-67890', '홍길동', '02-1234-5678', 'contact@seoulwelfare.kr',
  '서울 강남구 테헤란로 1', 'http://seoulwelfare.kr', 'B001', '복지 행사', TO_DATE('2025-06-01', 'YYYY-MM-DD'), TO_DATE('2025-06-10', 'YYYY-MM-DD'),
  '복지 행사 내용', '02-1234-5678', '노인 대상', 37.501, 127.039, '강남구', '서울시', '2025-05-01', '2025-06-01', SYSDATE, NULL, 'N', 'N'
);

INSERT INTO WELFARE_FACILITY (
  FACILITY_NO, FACILITY_API_SERVICE_ID, MEMBER_NO, FACILITY_NAME, FACILITY_KIND_CD, FACILITY_KIND_NM,
  FACILITY_BIZNO, OWNER, FACILITY_TEL, FACILITY_EMAIL, FACILITY_ADDR, FACILITY_HOMEPAGE, BUILDING_NO,
  EVENT_TITLE, EVENT_DATE_START, EVENT_DATE_END, EVENT_CONTENT, CONTACT_TEL, REQUIREMENT,
  LAT, LNG, REGION_DISTRICT, REGION_CITY, RCPTBGNDT, RCPTENDDT, JJ_TIME, UPDATED_AT, JJ_DEL_FL, ALARM_SENT_FL
) VALUES (
  'FAC002', 'FAC002', 2, '부산 복지센터', '02', '장애인복지시설', '234-56-78901', '이순신', '051-9876-5432', 'contact@busanwelfare.kr',
  '부산 해운대구 센텀중앙로 55', 'http://busanwelfare.kr', 'B002', '복지 캠페인', TO_DATE('2025-06-05', 'YYYY-MM-DD'), TO_DATE('2025-06-15', 'YYYY-MM-DD'),
  '장애인 지원 캠페인', '051-9876-5432', '장애인 대상', 35.179, 129.075, '해운대구', '부산시', '2025-05-05', '2025-06-05', SYSDATE, NULL, 'N', 'N'
);

INSERT INTO WELFARE_FACILITY (
  FACILITY_NO, FACILITY_API_SERVICE_ID, MEMBER_NO, FACILITY_NAME, FACILITY_KIND_CD, FACILITY_KIND_NM,
  FACILITY_BIZNO, OWNER, FACILITY_TEL, FACILITY_EMAIL, FACILITY_ADDR, FACILITY_HOMEPAGE, BUILDING_NO,
  EVENT_TITLE, EVENT_DATE_START, EVENT_DATE_END, EVENT_CONTENT, CONTACT_TEL, REQUIREMENT,
  LAT, LNG, REGION_DISTRICT, REGION_CITY, RCPTBGNDT, RCPTENDDT, JJ_TIME, UPDATED_AT, JJ_DEL_FL, ALARM_SENT_FL
) VALUES (
  'FAC003', 'FAC003', 3, '대구 복지센터', '01', '노인복지시설', '345-67-89012', '장보고', '053-1234-5678', 'contact@daeguwelfare.kr',
  '대구 중구 중앙대로 77', 'http://daeguwelfare.kr', 'B003', '복지 세미나', TO_DATE('2025-06-10', 'YYYY-MM-DD'), TO_DATE('2025-06-20', 'YYYY-MM-DD'),
  '복지 세미나 내용', '053-1234-5678', '노인 대상', 35.872, 128.602, '중구', '대구시', '2025-05-10', '2025-06-10', SYSDATE, NULL, 'N', 'N'
);

INSERT INTO WELFARE_FACILITY (
  FACILITY_NO, FACILITY_API_SERVICE_ID, MEMBER_NO, FACILITY_NAME, FACILITY_KIND_CD, FACILITY_KIND_NM,
  FACILITY_BIZNO, OWNER, FACILITY_TEL, FACILITY_EMAIL, FACILITY_ADDR, FACILITY_HOMEPAGE, BUILDING_NO,
  EVENT_TITLE, EVENT_DATE_START, EVENT_DATE_END, EVENT_CONTENT, CONTACT_TEL, REQUIREMENT,
  LAT, LNG, REGION_DISTRICT, REGION_CITY, RCPTBGNDT, RCPTENDDT, JJ_TIME, UPDATED_AT, JJ_DEL_FL, ALARM_SENT_FL
) VALUES (
  'FAC004', 'FAC004', 4, '광주 복지센터', '03', '아동복지시설', '456-78-90123', '세종대왕', '062-9876-5432', 'contact@gwangjuwelfare.kr',
  '광주 동구 금남로 20', 'http://gwangjuwelfare.kr', 'B004', '복지 지원', TO_DATE('2025-06-15', 'YYYY-MM-DD'), TO_DATE('2025-06-25', 'YYYY-MM-DD'),
  '복지 지원 내용', '062-9876-5432', '아동 대상', 35.159, 126.853, '동구', '광주시', '2025-05-15', '2025-06-15', SYSDATE, NULL, 'N', 'N'
);

INSERT INTO WELFARE_FACILITY (
  FACILITY_NO, FACILITY_API_SERVICE_ID, MEMBER_NO, FACILITY_NAME, FACILITY_KIND_CD, FACILITY_KIND_NM,
  FACILITY_BIZNO, OWNER, FACILITY_TEL, FACILITY_EMAIL, FACILITY_ADDR, FACILITY_HOMEPAGE, BUILDING_NO,
  EVENT_TITLE, EVENT_DATE_START, EVENT_DATE_END, EVENT_CONTENT, CONTACT_TEL, REQUIREMENT,
  LAT, LNG, REGION_DISTRICT, REGION_CITY, RCPTBGNDT, RCPTENDDT, JJ_TIME, UPDATED_AT, JJ_DEL_FL, ALARM_SENT_FL
) VALUES (
  'FAC005', 'FAC005', 5, '인천 복지센터', '01', '노인복지시설', '567-89-01234', '유관순', '032-5566-7788', 'contact@incheonwelfare.kr',
  '인천 남동구 예술로 100', 'http://incheonwelfare.kr', 'B005', '복지 설명회', TO_DATE('2025-06-20', 'YYYY-MM-DD'), TO_DATE('2025-06-30', 'YYYY-MM-DD'),
  '복지 설명회 내용', '032-5566-7788', '노인 대상', 37.456, 126.705, '남동구', '인천시', '2025-05-20', '2025-06-20', SYSDATE, NULL, 'N', 'N'
);


SELECT * FROM WELFARE;
-- WELFARE
INSERT INTO WELFARE (
  SERVICE_NO, API_SERVICE_ID, MEMBER_NO, AGENCY, SERVICE_NAME, DESCRIPTION, CATEGORY, RECEPTION_METHOD,
  RECEPTION_START, RECEPTION_END, URL, SERVICE_PAY, LAT, LNG, REGION_DISTRICT, REGION_CITY,
  JJ_TIME, UPDATED_AT, JJ_DEL_FL, ALARM_SENT_FL
) VALUES (
  1, 'SVC001', 1, '서울복지재단', '노인 돌봄 서비스', '노인을 위한 돌봄 및 지원 서비스', '노인', '온라인 신청',
  '2025-06-01', '2025-06-30', 'http://seoulwelfare.or.kr/service1', 0, 37.501, 127.039, '강남구', '서울시',
  SYSDATE, NULL, 'N', 'N'
);

INSERT INTO WELFARE (
  SERVICE_NO, API_SERVICE_ID, MEMBER_NO, AGENCY, SERVICE_NAME, DESCRIPTION, CATEGORY, RECEPTION_METHOD,
  RECEPTION_START, RECEPTION_END, URL, SERVICE_PAY, LAT, LNG, REGION_DISTRICT, REGION_CITY,
  JJ_TIME, UPDATED_AT, JJ_DEL_FL, ALARM_SENT_FL
) VALUES (
  2, 'SVC002', 2, '부산복지재단', '장애인 지원 프로그램', '장애인 복지 지원 및 상담', '장애인', '전화 신청',
  '2025-06-05', '2025-07-05', 'http://busanwelfare.or.kr/service2', 0, 35.179, 129.075, '해운대구', '부산시',
  SYSDATE, NULL, 'N', 'N'
);

INSERT INTO WELFARE (
  SERVICE_NO, API_SERVICE_ID, MEMBER_NO, AGENCY, SERVICE_NAME, DESCRIPTION, CATEGORY, RECEPTION_METHOD,
  RECEPTION_START, RECEPTION_END, URL, SERVICE_PAY, LAT, LNG, REGION_DISTRICT, REGION_CITY,
  JJ_TIME, UPDATED_AT, JJ_DEL_FL, ALARM_SENT_FL
) VALUES (
  3, 'SVC003', 3, '대구복지센터', '아동 복지 서비스', '아동 복지 및 교육 지원 프로그램', '아동', '방문 신청',
  '2025-06-10', '2025-07-10', 'http://daeguwelfare.or.kr/service3', 0, 35.872, 128.602, '중구', '대구시',
  SYSDATE, NULL, 'N', 'N'
);

INSERT INTO WELFARE (
  SERVICE_NO, API_SERVICE_ID, MEMBER_NO, AGENCY, SERVICE_NAME, DESCRIPTION, CATEGORY, RECEPTION_METHOD,
  RECEPTION_START, RECEPTION_END, URL, SERVICE_PAY, LAT, LNG, REGION_DISTRICT, REGION_CITY,
  JJ_TIME, UPDATED_AT, JJ_DEL_FL, ALARM_SENT_FL
) VALUES (
  4, 'SVC004', 4, '광주복지센터', '저소득층 지원', '저소득층을 위한 금융 및 생활 지원', '저소득층', '온라인/전화',
  '2025-06-15', '2025-07-15', 'http://gwangjuwelfare.or.kr/service4', 0, 35.159, 126.853, '동구', '광주시',
  SYSDATE, NULL, 'N', 'N'
);

INSERT INTO WELFARE (
  SERVICE_NO, API_SERVICE_ID, MEMBER_NO, AGENCY, SERVICE_NAME, DESCRIPTION, CATEGORY, RECEPTION_METHOD,
  RECEPTION_START, RECEPTION_END, URL, SERVICE_PAY, LAT, LNG, REGION_DISTRICT, REGION_CITY,
  JJ_TIME, UPDATED_AT, JJ_DEL_FL, ALARM_SENT_FL
) VALUES (
  5, 'SVC005', 5, '인천복지재단', '청소년 지원 프로그램', '청소년의 교육 및 상담 지원', '청소년', '방문 신청',
  '2025-06-20', '2025-07-20', 'http://incheonwelfare.or.kr/service5', 0, 37.456, 126.705, '남동구', '인천시',
  SYSDATE, NULL, 'N', 'N'
);
SELECT * FROM WELFARE;
-- BOARD_TYPE 
INSERT INTO BOARD_TYPE (BOARD_CODE, BOARD_NAME) VALUES (1, '공지');
INSERT INTO BOARD_TYPE (BOARD_CODE, BOARD_NAME) VALUES (2, '문의');
INSERT INTO BOARD_TYPE (BOARD_CODE, BOARD_NAME) VALUES (3, '우리동네');
SELECT * FROM BOARD_TYPE;
COMMIT;


-- BOARD
INSERT INTO BOARD (
  BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, BOARD_UPDATE,
  BOARD_DEL_FL, BOARD_ANSWER, BOARD_TYPE, STAR_COUNT, POST_TYPE,
  BOARD_REPORT_COUNT, MEMBER_NO, API_SERVICE_ID, FACILITY_API_SERVICE_ID
) VALUES (
  1, '자유게시판 글 1', '내용 1', SYSDATE - 5, NULL,
  'N', 'N', 3, 4, '자유',
  0, 1, 'SVC001', 'FAC001'
);

INSERT INTO BOARD (
  BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, BOARD_UPDATE,
  BOARD_DEL_FL, BOARD_ANSWER, BOARD_TYPE, STAR_COUNT, POST_TYPE,
  BOARD_REPORT_COUNT, MEMBER_NO, API_SERVICE_ID, FACILITY_API_SERVICE_ID
) VALUES (
  2, '자유게시판 글 2', '내용 2', SYSDATE - 4, NULL,
  'N', 'N', 3, 3, '자유',
  0, 2, 'SVC002', 'FAC002'
);

INSERT INTO BOARD (
  BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, BOARD_UPDATE,
  BOARD_DEL_FL, BOARD_ANSWER, BOARD_TYPE, STAR_COUNT, POST_TYPE,
  BOARD_REPORT_COUNT, MEMBER_NO, API_SERVICE_ID, FACILITY_API_SERVICE_ID
) VALUES (
  3, '자유게시판 글 3', '내용 3', SYSDATE - 3, NULL,
  'N', 'N', 3, 5, '자유',
  0, 3, 'SVC003', 'FAC003'
);

INSERT INTO BOARD (
  BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, BOARD_UPDATE,
  BOARD_DEL_FL, BOARD_ANSWER, BOARD_TYPE, STAR_COUNT, POST_TYPE,
  BOARD_REPORT_COUNT, MEMBER_NO, API_SERVICE_ID, FACILITY_API_SERVICE_ID
) VALUES (
  4, '자유게시판 글 4', '내용 4', SYSDATE - 2, NULL,
  'N', 'N', 3, 2, '자유',
  0, 4, 'SVC004', 'FAC004'
);

INSERT INTO BOARD (
  BOARD_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_DATE, BOARD_UPDATE,
  BOARD_DEL_FL, BOARD_ANSWER, BOARD_TYPE, STAR_COUNT, POST_TYPE,
  BOARD_REPORT_COUNT, MEMBER_NO, API_SERVICE_ID, FACILITY_API_SERVICE_ID
) VALUES (
  5, '자유게시판 글 5', '내용 5', SYSDATE - 1, NULL,
  'N', 'N', 3, 1, '자유',
  0, 5, 'SVC005', 'FAC005'
);
SELECT * FROM BOARD;
COMMIT;


-- 전체 게시글 검색 (삭제되지 않은 글만)
SELECT
  BOARD_NO,
  BOARD_TITLE,
  BOARD_CONTENT,
  BOARD_DATE,
  BOARD_UPDATE,
  BOARD_TYPE,
  STAR_COUNT,
  POST_TYPE,
  BOARD_REPORT_COUNT,
  MEMBER_NO,
  API_SERVICE_ID,
  FACILITY_API_SERVICE_ID
FROM BOARD
WHERE BOARD_DEL_FL = 'N'
ORDER BY BOARD_DATE DESC;

-- 특정 게시판 유형별 검색 (예: 우리동네 게시판만)
SELECT
  BOARD_NO,
  BOARD_TITLE,
  BOARD_CONTENT,
  BOARD_DATE,
  BOARD_TYPE,
  POST_TYPE,
  MEMBER_NO
FROM BOARD
WHERE BOARD_DEL_FL = 'N'
  AND BOARD_TYPE = 3  -- 우리동네 게시판 코드 (1:공지, 2:문의, 3:우리동네)
ORDER BY BOARD_DATE DESC;


-- 키워드 포함 검색 (제목 또는 내용에 검색어 포함)
SELECT
  BOARD_NO,
  BOARD_TITLE,
  BOARD_CONTENT,
  BOARD_DATE,
  BOARD_TYPE,
  POST_TYPE,
  MEMBER_NO
FROM BOARD
WHERE BOARD_DEL_FL = 'N'
  AND (BOARD_TITLE LIKE '%' || '제목' || '%'
       OR BOARD_CONTENT LIKE '%' || '내용' || '%')
ORDER BY BOARD_DATE DESC;


-- 특정 회원이 작성한 게시글 검색
SELECT
  BOARD_NO,
  BOARD_TITLE,
  BOARD_CONTENT,
  BOARD_DATE,
  BOARD_TYPE,
  POST_TYPE
FROM BOARD
WHERE BOARD_DEL_FL = 'N'
  AND MEMBER_NO = 1  -- 예: MEMBER_NO가 1인 경우
ORDER BY BOARD_DATE DESC;


-- 채팅방 5개 생성
INSERT INTO MEMBER_CHAT_ROOM (CHAT_ROOM_NO, OPEN_MEMBER, PARTICIPANT, CHAT_CREATE_DATE, CHAT_ROOM_DEL_FL)
VALUES (1, 1, 2, SYSDATE - 10, 'N');

INSERT INTO MEMBER_CHAT_ROOM (CHAT_ROOM_NO, OPEN_MEMBER, PARTICIPANT, CHAT_CREATE_DATE, CHAT_ROOM_DEL_FL)
VALUES (2, 2, 3, SYSDATE - 9, 'N');

INSERT INTO MEMBER_CHAT_ROOM (CHAT_ROOM_NO, OPEN_MEMBER, PARTICIPANT, CHAT_CREATE_DATE, CHAT_ROOM_DEL_FL)
VALUES (3, 3, 4, SYSDATE - 8, 'N');

INSERT INTO MEMBER_CHAT_ROOM (CHAT_ROOM_NO, OPEN_MEMBER, PARTICIPANT, CHAT_CREATE_DATE, CHAT_ROOM_DEL_FL)
VALUES (4, 4, 5, SYSDATE - 7, 'N');

INSERT INTO MEMBER_CHAT_ROOM (CHAT_ROOM_NO, OPEN_MEMBER, PARTICIPANT, CHAT_CREATE_DATE, CHAT_ROOM_DEL_FL)
VALUES (5, 5, 1, SYSDATE - 6, 'N');

-- 채팅 메시지 5개 저장
INSERT INTO MEMBER_CHAT_MESSAGE (CHAT_NO, SENDER_NO, CHAT_CONTENT, CHAT_READ_FL, CHAT_SEND_DATE, CHAT_CONTENT_DEL_FL, CHAT_ROOM_NO)
VALUES (1, 1, '안녕하세요!', 'N', SYSDATE - 10, 'N', 1);

INSERT INTO MEMBER_CHAT_MESSAGE (CHAT_NO, SENDER_NO, CHAT_CONTENT, CHAT_READ_FL, CHAT_SEND_DATE, CHAT_CONTENT_DEL_FL, CHAT_ROOM_NO)
VALUES (2, 2, '안녕하세요, 반가워요!', 'N', SYSDATE - 9, 'N', 2);

INSERT INTO MEMBER_CHAT_MESSAGE (CHAT_NO, SENDER_NO, CHAT_CONTENT, CHAT_READ_FL, CHAT_SEND_DATE, CHAT_CONTENT_DEL_FL, CHAT_ROOM_NO)
VALUES (3, 3, '오늘 일정은 어떻게 되나요?', 'N', SYSDATE - 8, 'N', 3);

INSERT INTO MEMBER_CHAT_MESSAGE (CHAT_NO, SENDER_NO, CHAT_CONTENT, CHAT_READ_FL, CHAT_SEND_DATE, CHAT_CONTENT_DEL_FL, CHAT_ROOM_NO)
VALUES (4, 4, '좋은 하루 되세요!', 'N', SYSDATE - 7, 'N', 4);

INSERT INTO MEMBER_CHAT_MESSAGE (CHAT_NO, SENDER_NO, CHAT_CONTENT, CHAT_READ_FL, CHAT_SEND_DATE, CHAT_CONTENT_DEL_FL, CHAT_ROOM_NO)
VALUES (5, 5, '다음에 또 연락해요.', 'N', SYSDATE - 6, 'N', 5);


SELECT
  mcm.CHAT_NO,
  mcm.SENDER_NO,
  mcm.CHAT_CONTENT,
  mcm.CHAT_READ_FL,
  mcm.CHAT_SEND_DATE,
  mcm.CHAT_ROOM_NO
FROM MEMBER_CHAT_MESSAGE mcm
JOIN MEMBER_CHAT_ROOM mcr ON mcm.CHAT_ROOM_NO = mcr.CHAT_ROOM_NO
WHERE (mcr.OPEN_MEMBER = 1 OR mcr.PARTICIPANT = 1)
  AND mcm.CHAT_CONTENT LIKE '%' || '안녕' || '%'
  AND mcm.CHAT_CONTENT_DEL_FL = 'N'
ORDER BY mcm.CHAT_SEND_DATE DESC;
  

INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('강남구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('강동구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('강북구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('강서구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('관악구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('광진구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('구로구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('금천구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('노원구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('도봉구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('동대문구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('동작구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('마포구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('서대문구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('서초구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('성동구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('성북구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('송파구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('양천구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('영등포구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('용산구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('은평구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('종로구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('중구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('중랑구', '서울특별시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('강서구', '부산광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('금정구', '부산광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('기장군', '부산광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('남구', '부산광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('동구', '부산광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('동래구', '부산광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('부산진구', '부산광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('북구', '부산광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('사상구', '부산광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('사하구', '부산광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('서구', '부산광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('수영구', '부산광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('연제구', '부산광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('영도구', '부산광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('중구', '부산광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('해운대구', '부산광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('남구', '대구광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('달서구', '대구광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('달성군', '대구광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('동구', '대구광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('북구', '대구광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('서구', '대구광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('수성구', '대구광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('중구', '대구광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('강화군', '인천광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('계양구', '인천광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('미추홀구', '인천광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('남동구', '인천광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('동구', '인천광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('부평구', '인천광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('서구', '인천광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('연수구', '인천광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('옹진군', '인천광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('중구', '인천광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('광산구', '광주광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('남구', '광주광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('동구', '광주광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('북구', '광주광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('서구', '광주광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('대덕구', '대전광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('동구', '대전광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('서구', '대전광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('유성구', '대전광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('중구', '대전광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('남구', '울산광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('동구', '울산광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('북구', '울산광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('중구', '울산광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('울주군', '울산광역시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('세종시', '세종특별자치시');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('가평군', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('고양시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('과천시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('광명시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('광주시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('구리시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('군포시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('김포시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('남양주시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('동두천시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('부천시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('성남시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('수원시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('시흥시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('안산시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('안성시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('안양시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('양주시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('양평군', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('여주시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('연천군', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('오산시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('용인시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('의왕시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('의정부시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('이천시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('파주시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('평택시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('포천시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('하남시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('화성시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('강릉시', '강원특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('고성군', '강원특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('동해시', '강원특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('삼척시', '강원특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('속초시', '강원특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('양구군', '강원특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('양양군', '강원특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('영월군', '강원특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('원주시', '강원특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('인제군', '강원특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('정선군', '강원특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('철원군', '강원특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('춘천시', '강원특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('태백시', '강원특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('평창군', '강원특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('홍천군', '강원특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('화천군', '강원특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('횡성군', '강원특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('괴산군', '충청북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('단양군', '충청북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('보은군', '충청북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('영동군', '충청북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('옥천군', '충청북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('음성군', '충청북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('제천시', '충청북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('증평군', '충청북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('진천군', '충청북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('청주시', '충청북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('충주시', '충청북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('계룡시', '충청남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('공주시', '충청남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('금산군', '충청남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('논산시', '충청남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('당진시', '충청남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('보령시', '충청남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('부여군', '충청남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('서산시', '충청남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('서천군', '충청남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('아산시', '충청남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('예산군', '충청남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('천안시', '충청남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('청양군', '충청남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('태안군', '충청남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('홍성군', '충청남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('고창군', '전라북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('군산시', '전라북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('김제시', '전라북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('남원시', '전라북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('무주군', '전라북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('부안군', '전라북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('순창군', '전라북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('완주군', '전라북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('익산시', '전라북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('임실군', '전라북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('장수군', '전라북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('전주시', '전라북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('정읍시', '전라북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('진안군', '전라북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('강진군', '전라남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('고흥군', '전라남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('곡성군', '전라남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('광양시', '전라남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('구례군', '전라남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('나주시', '전라남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('담양군', '전라남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('목포시', '전라남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('무안군', '전라남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('보성군', '전라남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('순천시', '전라남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('신안군', '전라남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('여수시', '전라남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('영광군', '전라남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('영암군', '전라남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('완도군', '전라남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('장성군', '전라남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('장흥군', '전라남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('진도군', '전라남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('함평군', '전라남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('해남군', '전라남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('화순군', '전라남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('경산시', '경상북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('경주시', '경상북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('고령군', '경상북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('구미시', '경상북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('군위군', '경상북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('김천시', '경상북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('문경시', '경상북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('봉화군', '경상북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('상주시', '경상북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('성주군', '경상북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('안동시', '경상북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('영덕군', '경상북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('영양군', '경상북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('영주시', '경상북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('영천시', '경상북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('예천군', '경상북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('울릉군', '경상북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('울진군', '경상북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('의성군', '경상북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('청도군', '경상북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('청송군', '경상북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('칠곡군', '경상북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('포항시', '경상북도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('거제시', '경상남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('거창군', '경상남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('고성군', '경상남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('김해시', '경상남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('남해군', '경상남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('밀양시', '경상남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('사천시', '경상남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('산청군', '경상남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('양산시', '경상남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('의령군', '경상남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('진주시', '경상남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('창녕군', '경상남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('창원시', '경상남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('통영시', '경상남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('하동군', '경상남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('함안군', '경상남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('함양군', '경상남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('합천군', '경상남도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('서귀포시', '제주특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('제주시', '제주특별자치도');




UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_GN/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '강남구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_JN/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '종로구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_JG/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '중구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_YS/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '용산구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_SD/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '성동구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_GJ/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '광진구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_DD/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '동대문구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_GD/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '강동구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_SP/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '송파구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_SC/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '서초구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_GA/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '관악구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_DJ/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '동작구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_YD/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '영등포구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_GC/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '금천구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_GR/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '구로구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_GS/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '강서구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_YC/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '양천구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_MP/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '마포구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_SM/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '서대문구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_EP/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '은평구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_NW/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '노원구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_JR/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '중랑구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_DB/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '도봉구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_SB/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '성북구';

UPDATE REGION
SET API_URL = 'http://openapi.seoul.go.kr:8088/%s/xml/fcltOpenInfo_GB/1/1000/'
WHERE REGION_CITY = '서울특별시'
  AND REGION_DISTRICT = '강북구';

SELECT * FROM REGION WHERE REGION_CITY = '서울특별시' AND REGION_DISTRICT = '강남구';
COMMIT;

SELECT *
FROM REGION
WHERE REGION_CITY = '강원도';

SELECT COLUMN_NAME
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'REGION'
  AND COLUMN_NAME = 'API_URL';




SELECT COLUMN_NAME 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'REGION';

SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'REGION';

SELECT * FROM REGION; 


SELECT COLUMN_NAME FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'REGION';

SELECT * 
FROM WELFARE_FACILITY 
WHERE FACILITY_ADDR LIKE '%송파구%';


SELECT * FROM REGION WHERE REGION_DISTRICT = '강남구';
SELECT
		DATASET_ID AS datasetId,
		UDDI_ID AS uddiId,
		API_URL AS apiUrl
		FROM REGION;
SELECT "API_URL" FROM REGION;
SELECT API_URL FROM REGION;

SELECT * FROM MEMBER;

SELECT * FROM REGION WHERE ROWNUM = 1;

SELECT column_name
FROM all_tab_columns
WHERE table_name = 'REGION';

INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('고양특례시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('성남특례시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('창원특례시', '경상남도');

INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('고창군', '전북특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('군산시', '전북특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('김제시', '전북특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('남원시', '전북특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('무주군', '전북특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('부안군', '전북특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('순창군', '전북특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('완주군', '전북특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('익산시', '전북특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('임실군', '전북특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('장수군', '전북특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('전주시', '전북특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('정읍시', '전북특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('진안군', '전북특별자치도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('수원특례시', '경기도');
INSERT INTO REGION (REGION_DISTRICT, REGION_CITY) VALUES ('용인특례시', '경기도');

COMMIT ;

-- 상세조회 sql문 

SELECT  
  B.BOARD_NO,
  B.BOARD_TITLE,
  B.BOARD_CONTENT,
  B.BOARD_DATE,
  B.BOARD_READ_COUNT,
  NVL(B.STAR_COUNT, 0) AS STAR_COUNT,
  
  -- 좋아요 수
  NVL((
    SELECT COUNT(*) 
    FROM BOARD_LIKE 
    WHERE BOARD_NO = B.BOARD_NO
  ), 0) AS LIKE_COUNT,
  
  -- 작성자 닉네임
  M.MEMBER_NICKNAME,

  -- 이미지 리스트
  NVL((
    SELECT LISTAGG(IMAGE_PATH, ',') WITHIN GROUP (ORDER BY IMAGE_ORDER)
    FROM BOARD_IMAGE 
    WHERE BOARD_NO = B.BOARD_NO
  ), '') AS IMAGE_LIST,

  -- 해시태그 리스트
  NVL((
    SELECT LISTAGG(H.HASHTAG_NAME, ',') 
    FROM BOARD_HASHTAG H
    WHERE H.BOARD_NO = B.BOARD_NO
  ), '') AS HASHTAGS,

  BT.BOARD_NAME,
  M.REGION_CITY,
  M.REGION_DISTRICT,
  B.API_SERVICE_ID,
  B.FACILITY_API_SERVICE_ID,

  -- 🎯 중복 방지된 POST_TYPE 1개만
  LS.POST_TYPE

FROM BOARD B

-- 기본 JOIN
JOIN MEMBER M ON B.MEMBER_NO = M.MEMBER_NO
JOIN BOARD_TYPE BT ON B.BOARD_TYPE = BT.BOARD_CODE

-- 🎯 POST_TYPE 중복 방지를 위한 서브쿼리
LEFT JOIN (
  SELECT BOARD_TYPE, MIN(POST_TYPE) AS POST_TYPE
  FROM LOCAL_SUBCATEGORY
  GROUP BY BOARD_TYPE
) LS ON B.BOARD_TYPE = LS.BOARD_TYPE

-- 조회 대상
WHERE B.BOARD_NO = 18;

